---
title: "GPTs"
---

### Introduction

::: {.callout-note title="Section Overview"}
This section contains custom GPTs I have setup to demonstrate different genAI use-cases. These GPTs are a mix of ones I have created for students in specific contexts, ones I use myself, and ones to demonstrate what is possible more than what is most useful.

In other words, these GPTs are not setup as exemplars for how you *must* nor *should* use genAI in all cases and contexts. Even where you find any useful, over time you will find that experimenting with your own prompts to customise responses to your specific use-cases is the best option. These GPTs are designed to help build a sense of what is possible and share examples of more complex prompts.

:::

### Important

::: {.callout-important title="No Paid Account Required"}
Please note, whilst these GPTs have been setup with ChatGPT you **do not** need to have a paid account to use them. All users are able to access and use custom GPTs.

At heart a custom GPT is merely a saved reuseable prompt with optional access to certain files pre-setup, alongside other settings. There is a smaller usage limit in chats with GPTs for free users, but copying and pasting the instructions into the start of a new regular chat will effectively recreate the same behaviour. So whilst a paid account is required to create custom GPTs this is basically 'convenience' and not 'essential' to have. And if you run into rate limits testing the GPTs, just try copying and pasting their instructions at the start of the regular chat.

Indeed, nor is using ChatGPT to set these up in any way an endorsement of ChatGPT itself and the instructions should work fine with most other genAI models. The custom GPT feature was merely the easiest way to setup and share such examples. Again, if using other genAI models, the instructions can be copied and pasted into a new chat - or any custom GPT equivalent they offer. Some minor tweaks to the instructions may be required - but that is same issue as face each time ChatGPT release a new model or a minor update to an existing one.
:::

### Overview of GPTs

**Meta**

- [Prompt Crafter](gpts/prompt-crafter.qmd)
- [Prompt Kit Builder](gpts/prompt-kit-builder.qmd)

**Sounding Boards**

- [Writing Aid](gpts/writing-aid.qmd)
- [LinguaTune](gpts/linguatune.qmd)
- [Word and Phrasing Finder](gpts/word-phrasing-finder.qmd)
- [Academic Exercises in Style](gpts/academic-exercises.qmd)
- [Lateral Storms](gpts/lateral-storms.qmd)

**Learning Aids**

- [Accessible Python](gpts/accessible-python.qmd)
- [RStudio Cloud Helper](gpts/rstudio-helper.qmd)
- [Polish Companion](gpts/polish-companion.qmd)
- [Theory Navigator](gpts/theory-navigator.qmd)

**Files, Web, Data**

- [UK Bull Dung Checker](gpts/uk-bull-dung.qmd)
- [Kapital Question](gpts/kapital-question.qmd)
- [UK SDG Insights](gpts/uk-sdg-insights.qmd)
- [Parser GPT](gpts/parser-gpt.qmd)

**Additional**

- [Spook School Slides](gpts/spook-school.qmd)
- [Exploring Home](gpts/exploring-home.qmd)
- [Textual Trouble](gpts/textual-trouble.qmd)
- [Simple Short Email Aid](gpts/simple-short-email.qmd)
- [Air Supply Not Found](gpts/air-supply-not-found.qmd)

### Explore Use-Cases

::: experiment
The full instructions for each GPT is shared to show how it was setup, alongside some 'conversation starters' and general notes on design decisions and limitations. Experiment with tweaking the instructions to tailor them to your use-cases and preferences.

Have a use-case not covered? Skim through the instructions and see if there is anything can adapt and modify to craft prompts for it.
:::

